### ISSUE TITLE
holy cow this is awesome!

### ISSUE THREAD

**Issue by goldenpipes** [KimbaWLion/DiscordBaseballBot#2]
hey there! ive been looking for something like this for quite awhile!

that said i cant seem to get it running.  I dont know a ton about python but i've installed all the dependencies and im running into this error:
```cmd
Traceback (most recent call last):
  File "MainEntryBot.py", line 61, in <module>
    error_msg = read_settings()
  File "MainEntryBot.py", line 22, in read_settings
    settings = json.load(data)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 6 column 28 (char 285)
```

I'm running python 3.7 x64, windows 10, pip is up to date and i did pip install discord.py, aiohttp.py, asyncio.py, bs4 packages

any pointers?

edit: I was able to get it running, had my pathing wrong in my settings.json.

how do i send a test message? testPost.py just yells at me:
```cmd
C:\Users\lewis\Desktop\DiscordBaseballBot\BaseballConsumer>python testPost.py
Traceback (most recent call last):
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 UNAUTHORIZED (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "testPost.py", line 39, in <module>
    client.run(TOKEN)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 598, in run
    return future.result()
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "C:\Users\lewis\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
```

**Comment by KimbaWLion** [comment]
Glad you like my bot!

When it comes to error logs.  The last line is the error that caused the issue.  In your edit's case it is 

`discord.errors.LoginFailure: Improper token has been passed.`

This sounds like there is an issue with your bot's token.  Did you set up your bot correctly and find the correct values for DISCORD_CLIENT_SECRET and DISCORD_TOKEN?

**Comment by goldenpipes** [comment]
i have the bot connected to discord just fine. its just not output anything.

it never seemed to pull any data, 

im assuming i have some paths wrong or something

**Comment by goldenpipes** [comment]
the settings.json is a bit confusing to me.
```json
{
    "DISCORD_CLIENT_ID": "DISCORD_CLIENT_ID",
    "DISCORD_CLIENT_SECRET": "DISCORD_CLIENT_SECRET",
    "DISCORD_TOKEN": "DISCORD_TOKEN",
    "DISCORD_GAME_THREAD_CHANNEL_ID": "DISCORD_GAME_THREAD_CHANNEL_ID",
    "GAME_THREAD_LOG": "<Path to game_thread.now>",
    "BOT_TIME_ZONE": "ET",
    "TEAM_TIME_ZONE": "ET",
    "TEAM_CODE": "nyn",
    "TEAM_ABBREV": "NYM",

    "GAME_THREAD_NOW": "./logs/game_thread.now"
}

```

 (I put in "C:\\Users\\lewis\\Desktop\\DiscordBaseballBot\\BaseballConsumer\\logs\\game_thread.now",)
for `"GAME_THREAD_LOG":`

and for the bottom one as well.

**Comment by goldenpipes** [comment]
is something supposed to generate the game_thread.now file? and im missing something or does the bot run the other python scripts that generate the game_thread.now?

**Comment by KimbaWLion** [comment]
Create a file named game_thread.now with nothing in it.  Do you have your TEAM_CODE  and TEAM_ABBREV set up correctly?

**Comment by goldenpipes** [comment]
pretty sure. ill post my cfg.
```json
{
    "DISCORD_CLIENT_ID": "601803826634293269",
    "DISCORD_CLIENT_SECRET": "fRpU_LDSlL0DYVkbHgQVuBA_Q3vqJvLR",
    "DISCORD_TOKEN": "NjAxODAzODI2NjM0MjkzMjY5.XTHoig.5GRsn7X4wMJZWbThVS3VaNyxYUA",
    "DISCORD_GAME_THREAD_CHANNEL_ID": "601805212914679831",
    "GAME_THREAD_LOG": "C:\\Users\\lewis\\Desktop\\DiscordBaseballBot\\BaseballConsumer\\logs\\game_thread.now",
    "BOT_TIME_ZONE": "CST",
    "TEAM_TIME_ZONE": "CST",
    "TEAM_CODE": "min",
    "TEAM_ABBREV": "MIN",
	
	"GAME_THREAD_NOW": "C:\\Users\\lewis\\Desktop\\DiscordBaseballBot\\BaseballConsumer\\logs\\game_thread.now"
}
```

**Comment by goldenpipes** [comment]
does the bot maybe not like those absolute paths?

**Comment by KimbaWLion** [comment]
If you have a windows machine, try using forward slashes "/" instead of back slashes "\". You do not need to use a backsplash before a forward slash (face/off vs. Face\\off)

**Comment by goldenpipes** [comment]
hmm let me try that

**Comment by goldenpipes** [comment]
the game_thread.now is still empty

**Comment by goldenpipes** [comment]
should i try this on ubuntu? i can spin up a VM quick

**Comment by KimbaWLion** [comment]
Legit I don't know, I've only tried this in windows. When I get home I'll post my settings.json

**Comment by KimbaWLion** [comment]
Is there anything being output to the console when you run the bot?

**Comment by goldenpipes** [comment]
```cmd
C:\Users\lewis\Desktop\DiscordBaseballBot>python BaseballConsumer\MainEntryBot.py
Logged in as
Robot Dick Bremer
601803826634293269
------
```
thats it

nothing else ever shows up

**Comment by goldenpipes** [comment]
4. in BaseballConsumer/BaseballConsumer.py, change line 27 to the path of the game_thread.now file.  (i.e. 'C:\Users...\game_thread.now')

line 27 in BaseballConsumer.py:
`SETTINGS_FILE = './settings.json'`

is this correct?

so i would have
`SETTINGS_FILE = 'C:/Users/lewis/desktop/DiscordBaseballBot/BaseballConsumer/Logs/game_thread.now'`

this kinda doesn't makes sense.

**Comment by KimbaWLion** [comment]
```
    "GAME_THREAD_LOG": "C:/Users/Username/PycharmProjects/DiscordBaseballBot/BaseballConsumer/logs/game_thread.now",
    "BOT_TIME_ZONE": "ET",
    "TEAM_TIME_ZONE": "ET",
    "TEAM_CODE": "nyn",
    "TEAM_ABBREV": "NYM",

    "GAME_THREAD_NOW": "./logs/game_thread.now"
}
```

**Comment by KimbaWLion** [comment]
In BaseballConsumer.py I have

`SETTINGS_FILE = './settings.json'`

**Comment by goldenpipes** [comment]
so step 4 is unnecessary?

**Comment by KimbaWLion** [comment]
Yup.  I moved the path into `settings.json` and forgot to update the instructions.  Good catch.

Heh, GAME_THREAD_NOW isn't even used.  Let me fix the instructions here

**Comment by KimbaWLion** [comment]
updated the files and instructions so there shouldn't be any conflicting steps

**Comment by goldenpipes** [comment]
👍 

how long before a game starts should `game_thread.now` start generating stuff?

**Comment by KimbaWLion** [comment]
game_thread.now should start generating stuff at game start time.  If the bot is running correctly you should see the output from the standardOut (the console output, not in a file) as:

```
[2019/07/21 09:59:26] Searching for day's URL...
Logged in as
NYM-Bot
<id>
------
[2019/07/21 09:59:27] Found day's URL: http://gd2.mlb.com/components/game/mlb/year_2019/month_07/day_21
[2019/07/21 09:59:27] Found game directory for team nyn: ['http://gd2.mlb.com/components/game/mlb/year_2019/month_07/day_21/gid_2019_07_21_nynmlb_sfnmlb_1/']
[2019/07/21 09:59:27] Searching the URL directory for updates : http://gd2.mlb.com/components/game/mlb/year_2019/month_07/day_21/gid_2019_07_21_nynmlb_sfnmlb_1/
[2019/07/21 09:59:28] Game has not started yet
[2019/07/21 09:59:38] Searching the URL directory for updates : http://gd2.mlb.com/components/game/mlb/year_2019/month_07/day_21/gid_2019_07_21_nynmlb_sfnmlb_1/
[2019/07/21 09:59:39] Game has not started yet
[2019/07/21 09:59:49] Searching the URL directory for updates : http://gd2.mlb.com/components/game/mlb/year_2019/month_07/day_21/gid_2019_07_21_nynmlb_sfnmlb_1/
[2019/07/21 09:59:50] Game has not started yet
...
```

**Comment by goldenpipes** [comment]
thats what i figured. I have no idea what i'm missing. any chance you could zip your working folder minus your settings.json ofc?

**Comment by goldenpipes** [comment]
i never see the searching for day;s URL part.

**Comment by KimbaWLion** [comment]
With the exception of settings.json, my code matches what's in github exactly.  

Could you post me what your output is?  Is it just the "Logged in as bot"?

**Comment by goldenpipes** [comment]
yup

**Comment by KimbaWLion** [comment]
Could you try 
```
    "TEAM_CODE": "nyn",
    "TEAM_ABBREV": "NYM"
```
to see if you can get the Mets game.  I doubt your teamcode is wrong but might as well check

**Comment by goldenpipes** [comment]
sure

**Comment by goldenpipes** [comment]
same output

**Comment by KimbaWLion** [comment]
Hmmmmmmmmmmmmmmm... I am at a loss of what could be the issue.

Could you put print statements (`print('asdf');`) in BaseballConsumer.py starting at line 308 so we can find out what line the bot fails at?

Also, do you have a discord account?  we can make the iteration of helping debug this quicker on there

**Comment by goldenpipes** [comment]
of course i do

**Comment by goldenpipes** [comment]
Goldenpipes#6891

**Comment by KimbaWLion** [comment]
The issues here were that the python version and the discord.py version were not working together.  The discord.py v1.2.3 is not backwards compatible with discord.py v0.16.7, making the bot not work (due to Discord.client.is_closed is now a function, not a variable).  Also discord.py v0.16.7 does not work with Python v3.7+ when it comes to asyncio.  

I added the required versions to the README so others downloading this bot will not run into the same issue
